cert-manager/trust-manager

- design/20210715.bundle-crd.md
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
> Adds design doc for bundle CRD

- OWNERS
- README.md
- deploy/charts/trust/Chart.yaml
- deploy/charts/trust/README.md
Should be automated, but this harmonizes the OWNERS file with the main cert-manager file, and updates the helm chart too. The helm chart update won't take effect until after another release - it's probably not worth doing a release straight away just for this, though.
Also, as part of [this PR for istio-csr](https://github.com/cert-manager/istio-csr/pull/116) I noticed that the header on a lot of our READMEs included invalid HTML. This fixes that, adds an artifacthub badge, and adds alt text for a11y.
> Update OWNERS + Fix broken HTML

- Makefile
- hack/boilerplate/boilerplate.py
- pkg/bundle/bundle_test.go
- pkg/bundle/controller.go
- pkg/bundle/sync_test.go
- pkg/bundle/util.go
- pkg/bundle/util_test.go
- pkg/webhook/validation_test.go
- test/env/data.go
Adds `go vet ./...` as part of the Makefile `lint` target.
Fixes all the `go vet` linting errors.
/assign @SgtCoDFish
> Makefile: go vet

- README.md
This corrects a broken link to the cert-manager.io doc site.
> docs: correct broken link to documentation

- Makefile
1. Adds `make chart` to generate a local helm chart for testing
2. Creates `$(BINDIR)` and subdirectories using order only dependencies (see details [in the cert-manager repo](https://github.com/cert-manager/cert-manager/tree/master/make#target-dependencies--prerequisites))
3. Use `$@` where possible
4. Adds release version as a variable since it's now used in more than one place
I'd probably also advocate changing `$(BINDIR)` to default to `_bin` for the [same reasons we did that in cert-manager](https://github.com/cert-manager/cert-manager/pull/5130) but that seemed maybe a change too far for this PR
> Add chart building + ensure BINDIR is created when running targets

- pkg/bundle/test/suite.go
I have started seeing quite a few transient test errors in CI because some integration test didn't reach a desired state in time.
This _may_ be because the CI runner is resource constrained, so I have increased the timeout here. Will watch this PR for a bit to see if this improves things or we have an actual bug here.
For me, running the tests locally always works.
/hold
> Increase timeout for bundle integration tests for desired state from 10s to 30s

- deploy/charts/trust/templates/deployment.yaml
Currently if we run `make e2e-setup-certmanager` in a cert-manager checkout, we'll install kyverno which will insist on a restrictive security context. That makes a lot of sense, and there's no reason we couldn't use the same restrictive context here.
This also adds `readOnlyRootFilesystem: true` which seems to work fine locally and seems a worthwhile thing to set early if we possibly can!
> add restrictive securitycontext for controller pod

- deploy/charts/trust/Chart.yaml
- deploy/charts/trust/README.md
Updates helm chart version to v0.1.2 after  https://github.com/cert-manager/trust/pull/47
Signed-off-by: joshvanl <me@joshvanl.dev>
> Updates Helm chart version to v0.1.2

- Dockerfile
- go.mod
- hack/tools/go.mod
Signed-off-by: joshvanl <me@joshvanl.dev>
Updates go modules and Docker image golang version to v1.19
/hold
Until [jetstack/testing](https://github.com/jetstack/testing/tree/master/config/jobs) has been updated
> Update go to v1.19

- pkg/webhook/validation.go
- pkg/webhook/validation_test.go
- pkg/webhook/webhook.go
fixes #29 
Currently, we have validation in the admission webhook to ensure that Bundle targets cannot be the same as another Bundle target. This makes no sense, since Bundles are cluster scoped resources and resulting targets (today only ConfigMaps) are named, and therefore namespaced, by the Bundle themselves. There can only be a single target per Bundle.
Basically, the current validation makes no sense, and we should remove it.
---
As an aside, we _might_ now be able to push all of these validations into the API schema itself and do away with needing a networked admission webhook all together (:smile:).
/assign @jakexks
> Remove same bundle target key validation check 

- test/env/data.go
The current timeout for this Eventually check is 1s. This is very prohibitive and often causes false negatives in CI runs which is a resource constrained environment.
> Update Eventually timeout to be 10s

- deploy/charts/trust-manager/Chart.yaml
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
Update Certificate resource used for webhook with self-signed issuer to include issuerRef and group. This is to avoid the BadConfig warning that gets logged when CertificateRequest resource is created. Resolves #56 
Signed-off-by: Sitaram IYER <sitaramkm@gmail.com>
> Update Certificate resource to include issuerRef and group.

- Dockerfile
- Makefile
- bundles/debian/Containerfile
- bundles/debian/build.sh
- bundles/debian/go.mod
- bundles/debian/main.go
- gcb/ci-update-debian-bundle.yaml
- hack/update-debian-ca-bundle.sh
- hack/wait-for-buildx.sh
- make/image-bundle-debian.mk
This only adds the build process so we can start generating these images regualarly, ahead of creating a trust-manager release which actually uses the images.
Also adds buildx provisioning and uses named a named buildx builder for trust-manager specifically.
The build is intended to be regularly scheduled in cloudbuild using the provided `gcb/ci-update-debian-bundle.yaml` file.
I'd propose currently that this takes the form of us creating a cloudbuild trigger and schedule by hand. I've done that in my own GCP project and confirmed it works as expected. Ideally we'd terraform this, but we don't have that infrastructure in place currently and I don't think this is the time to shave that yak!
See https://quay.io/repository/adjetstack/cert-manager-bundle-debian?tab=tags for an example of the …
> Add a static bundle sidecar container build 

- gcb/ci-update-debian-bundle.yaml
Also adds details on how to generate the secret!
> Update docker config to use a trust-manager-specific token

- pkg/bundle/bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
- pkg/bundle/test/suite.go
- pkg/util/pem.go
- pkg/util/pem_test.go
- pkg/webhook/validation_test.go
- test/dummy/certificates.go
- test/env/data.go
- test/smoke/suite.go
This function is intended to validate PEM inputs to ensure that the only contain certificates and that all certificates within are valid.
Also updates tests to use actual dummy PEM certificates rather than junk data. I think hardcoding certs here is fine - for now at least, we don't care if the certs expire in the future - we just care that they're valid PEM certificates.
> Add PEM verification function

- Dockerfile
- Makefile
- make/trust-package-debian.mk
- trust-packages/debian/Containerfile
This will enable devs with a custom GOPROXY to leverage it when building + testing trust-manager!
NOTE: I couldn't see a way to do this without build args using `docker buildx`. Maybe I missed the equivalent of `docker build -e GOPROXY` but in any case I can see why they maybe wouldn't want that for buildx.
> Pass GOPROXY to build environment

- test/env/data.go
Before this change, the function was checking if a bundle had synced to the first namespace returned and not checking if all namespaces had synced the bundle
Spotted while refactoring tests more widely but this seems too important to leave!
> Fix logic error in trust-manager tests

- make/trust-package-debian.mk
This was moved into Makefile in #82 !
> trivial: remove second definition of _COMMA

- Makefile
- cmd/app/app.go
- cmd/validate-trust-package/main.go
- hack/boilerplate/boilerplate.py
- trust-packages/debian/build.sh
Also adds a validator for trust packages, which we'll use to ensure we don't publish packages which trust-manager won't be able to load.
This PR doesn't actually _use_ the validator yet - that'll come in a separate PR to solve the chicken and egg problem (we want the build for the trust-package to happen in a container, but don't want to share anything from the local environment with that container. So we'll `go install github.com/cert-manager/trust-manager/cmd/validate-trust-package@latest` during the build of the trust package, but to do that we need to publish the build for that first)
> Remove type from trust packages + add validation on package build

- trust-packages/debian/Containerfile
- trust-packages/debian/build.sh
Probably it would be ideal to use a tagged version of the validator rather than `main` in the future, but for now we don't have a tag which includes the validator.
For now, since it's unlikely to change much, it should be fine to use `main`.
> Validate CA package during build

- pkg/bundle/bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/cache/cache.go
- pkg/bundle/controller.go
- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
Here, we incorrectly assume that the client is a non-cached client:
https://github.com/cert-manager/trust-manager/blob/f2da89271eb887093f434a4e79b80d1fee02a212/pkg/bundle/bundle.go#L57-L60
This results in caching all these resources fully. Additionally, we are already caching the metadata-only representation of these resources, effectively caching each resource twice (more info: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/options.go#L103-L132).
In this PR, I fix this issue and also rename the `client` field to `directClient` to make clear that this client is not cached.
Also, I simplified the cache.go code a bit by using an external library.
fixes #91
> Fix non-cached client

- Makefile
- deploy/charts/trust-manager/templates/clusterrole.yaml
- test/kind-cluster.yaml
This should enable trust-manager to work in OpenShift!
Based on a [slack thread](https://kubernetes.slack.com/archives/C4NV3DWUC/p1675277465934999) which reported the issue
> Add missing permission to update bundle finalizers

- Makefile
- README.md
- deploy/charts/trust-manager/Chart.yaml
- deploy/charts/trust-manager/README.md
While the README updates weren't really needed and we're aiming to have full documentation on the website, I think it's valuable to have the example bundle in the README too.
> Bumps + doc updates for 0.4.0

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.yaml
- hack/update-helm-docs.sh
This should've been done before the tag + release of `v0.4.0` but was missed. We agreed in standup on 2023-02-03 that it was fine to release the container images built from the v0.4.0 tag and use this commit for releasing the chart.
> Bump values in helm chart

- design/20220722-publicbundle.md
This proposal introduces a design by which bundles are stored in sidecar containers and consumed from a shared path by the controller container.
> Add a design for public trust bundles

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/NOTES.txt
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.yaml
The init container is a bit noisy when distributing in-house trust in environments with no internet connection.
> helm: make installation of default trust package optional

- pkg/bundle/sync.go
This should hopefully make these files deterministic!
Also changes comment for default JKS password
This was inspired by a [comment](https://github.com/cert-manager/trust-manager/pull/122#discussion_r1179954947) by @vinzent on #122 which initially implemented JKS support.
> Use ordered aliases when creating JKS files

- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/metrics-service.yaml
- deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
- deploy/charts/trust-manager/templates/serviceaccount.yaml
- deploy/charts/trust-manager/templates/webhook.yaml
This is very useful in combination with Helm template. It makes sure that all templated resources have the namespace set. This way, it is not possible to `k apply -f` in a different namespace; potentially breaking some of our references that contain namespace names.
> Explicitly define resource namespaces in Helm chart

- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
- pkg/util/pem.go
- test/dummy/certificates.go
- test/env/data.go
- test/integration/bundle/suite.go
Each commit should have a descriptive commit message.
This PR is intended to address the issue raised in [this comment](https://github.com/cert-manager/trust-manager/pull/122#issuecomment-1529783592) where two certs with the same Issuer field would be de-duped when added to the JKS file, despite them being different certificates.
> Ensure unique aliases in JKS files

- Makefile
- deploy/charts/trust-manager/Chart.yaml
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.yaml
Note that the prerelease annotation wasn't committed for v0.5.0-beta.0 (in #125 ) and I added it manually before I generated the helm chart. I've added it here, so we just need to remember to update that annotation when we release the next non-prerelease version!
> Bump version to v0.5.0-beta.1

- pkg/apis/trust/v1alpha1/types_bundle.go
This will improve [this page](https://cert-manager.io/docs/projects/trust-manager/api-reference/) (after a followup PR for the website!)
I now realise (of course, just after the official release :grin: ) that JKS shouldn't be a `KeySelector`, it should be a `JKSFormat` or something. That'll have to be fixed in `v1alpha2` or `v1beta1`!
> Add description for JKS field for better docs

- README.md
- deploy/charts/trust/Chart.yaml
- deploy/charts/trust/README.md
- deploy/charts/trust/templates/NOTES.txt
The intent here is to encourage users to use 'trust-manager' instead.
This was discussed in the cert-manager biweekly meeting on 2023-06-01.
> Add deprecation notes for the old cert-manager-trust name

- Makefile
The previous version would always generate a chart with appVersion == version, which we explicitly don't want here. Since we should ideally never change this again, it seems fine to hardcode and add a comment to warn!
> Manually change chart packaging and add clarifications

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/values.yaml
If using cert-manager with the default approver disabled, it's a pain to install trust-manager since it requires manual approval of the CertificateRequest which is issued for the webhook.
This adds an option to create a CertificateRequestPolicy which approver-policy can use to auto-approve the CR.
This was tested with:
```bash
#!/usr/bin/env bash
set -exu -o pipefail
rm  ./bin/chart/trust-manager-v0.5.0.tgz && make chart
helm template trust-manager ./bin/chart/trust-manager-v0.5.0.tgz --namespace default --set app.trust.namespace=default --set approverPolicy.enabled=true > bin/templated.yaml
helm install \
cert-manager jetstack/cert-manager \
--namespace cert-manager \
--create-namespace \
--version v1.12.0 \
--set installCRDs=true \
--set …
```
> Add support for approver policy

- pkg/bundle/sync.go
- pkg/webhook/validation.go
- pkg/webhook/validation_test.go
This fixes #133 - an issue where setting `useDefaultCAs: false` would cause validation (and also sync) errors.
In order to support this the validation code needed to change slightly. It now counts the number of sources in a bundle and will fail if that count is still zero after inspection. Setting `useDefaultCAs: true` is considered a source for this count, but `useDefaultCAs: false` is not.
So these specs are valid:
```yaml
spec:
sources:
- useDefaultCAs: true
```
```yaml
spec:
sources:
- secret:
name: "our-org-ca"
key: "ca.crt"
```
```yaml
spec:
sources:
- useDefaultCAs: true
- secret:
name: "our-org-ca"
key: "ca.crt"
```
```yaml
spec:
sources:
- useDefaultCAs: false
- secret:
name: "our-org-ca"
key: "ca.crt"
```
But this one is not:
```yaml
spec:
sources:
- useDefaultCAs: false
> Setting useDefaultCAs: false no longer causes failures

- deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- hack/boilerplate/boilerplate.go.txt
- hack/update-codegen.sh
Codegen wasn't working on a new checkout running `make generate` because the boilerplate was missing and the generated deepcopy was being created under an additional `github.com/cert-manager/trust-manager` hierarchy.
This PR puts the boilerplate in (based on the existing deepcopy boilerplate), fixes the pathing, and includes a couple of changes to generated files that hadn't been applied.
> Fix code generation

- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
Before filing a PR to add support for PKCS#12 truststores (ref. remaining in https://github.com/cert-manager/trust-manager/issues/17), I think it makes sense to slightly refactor the JKS truststore support introduced in https://github.com/cert-manager/trust-manager/pull/122. I think it will make the follow-up PR easier to review.
> Refactor CM binary data reconcile preparing for PKCS#12 support

- deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
This a follow-up PR to https://github.com/cert-manager/trust-manager/pull/163. Somehow I (and also reviewers) did not see that the Bundle CRD wasn't updated. 🤣 Sorry! In my defense, I can only say that the controllers I usually work with (on-prem) have CI to verify that generated files are up-to-date. I will create an issue suggesting the same in this project.
I should probably also update the API docs somewhere, or is that automated?
> Add support for PKCS12 truststores (update CRD)

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/values.yaml
The cert-manager ServiceAccount is not fixed and so can vary between different installations. [1] [2]
cert-manager users might well want to customise it, and we should support those users in trust-manager!
ℹ️ This also removes the namespace from the CertificateRequestPolicy, since that resource is cluster scoped and so passing a namespace here is a no-op!
[1] https://github.com/cert-manager/cert-manager/blob/cab2b3b68ca834b60931fd76d1fb74f757a03550/deploy/charts/cert-manager/templates/serviceaccount.yaml#L10
[2] https://github.com/cert-manager/cert-manager/blob/cab2b3b68ca834b60931fd76d1fb74f757a03550/deploy/charts/cert-manager/values.yaml#L108
> Allow user to specify the name of cert-manager's ServiceAccount

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/_helpers.tpl
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.yaml
I'm standardising the image options across all our charts (https://github.com/cert-manager/cert-manager/issues/6329).
> HELM: add options for configuring image

- pkg/bundle/bundle.go
- pkg/bundle/controller.go
- pkg/bundle/sync.go
- test/integration/bundle/suite.go
@erikgb noticed that the client-side-apply to server-side-apply migration functions are not working as expected (https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1694172356236499).
In https://github.com/cert-manager/trust-manager/pull/89, I made the wrong assumption that the fieldmanager was set to "trust-manager" in previous versions.
In this PR, I fixed this mistake. I also added a test to make sure that the confimap resources are also correctly migrated.
> BUGFIX: fix migration from csa to ssa

- cmd/trust-manager/app/app.go
This PR removes the obsolete TODO in controller bootstrap, ref. https://github.com/cert-manager/trust-manager/pull/187#pullrequestreview-1645832202 and ensures that we only cache full configmaps in source namespace.
/cc @inteon
> Cleanup controller bootstrap

- pkg/util/cert_pool.go
- pkg/util/cert_pool_test.go
- pkg/util/pem.go
- test/dummy/certificates.go
This PR is related to the issue `de-duplicate CA from the trust bundle` #155 
It add feature of certificates de-duplication, meaning to exclude certificates which were already added to a certificates bundle, thus save memory.
> Add certificates deduplication feature

- pkg/bundle/bundle.go
- pkg/bundle/sync.go
This PR adapts the SSA migration code to the controller-runtime regression introduced in c/r version 0.15.0 and fixed by https://github.com/kubernetes-sigs/controller-runtime/pull/2435.
/cc @inteon
> Fix SSA migration field managers

- deploy/charts/trust-manager/templates/clusterrole.yaml
When verifying v0.7.0-alpha.1 in our clusters, I notice the following error:
````
E1006 16:12:20.394650       1 bundle.go:134] trust/bundle "msg"="failed to migrate bundle status" "error"="bundles.trust.cert-manager.io \"my-bundle\" is forbidden: User \"system:serviceaccount:cert-manager:trust-manager\" cannot update resource \"bundles\" in API group \"trust.cert-manager.io\" at the cluster scope" "bundle"="my-bundle"
````
I believe this patch should fix this.
/cc @inteon
> fix: add missing RBAC for CSA->SSA migration of bundles/status

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.yaml
Spotted these while working on something unrelated and couldn't help but shave the yak!
> Update a couple of instances of the old project name

- Dockerfile
- Makefile
- hack/update-codegen.sh
Make won't update files when a variable changes unless that variable is somehow included as a dependency for a target or in the path of the name of the target.
This commit adds versions to the paths of all tools we depend on, so that when one user bumps version numbers, everyone else won't need to run `make clean`.
> Vendor dependencies correctly

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/_helpers.tpl
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/templates/clusterrolebinding.yaml
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/metrics-service.yaml
- deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
- deploy/charts/trust-manager/templates/rolebinding.yaml
- deploy/charts/trust-manager/templates/serviceaccount.yaml
- deploy/charts/trust-manager/templates/webhook.yaml
- deploy/charts/trust-manager/values.yaml
This is based on cert-manager's helm chart override and resolves #145
> allow setting namespace for helm chart

- Makefile
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/clusterrole.yaml
- deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- deploy/charts/trust-manager/values.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
- pkg/bundle/bundle.go
- pkg/bundle/controller.go
- pkg/bundle/internal/ssa_client/configmap.go
- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
- pkg/webhook/validation.go
- pkg/webhook/validation_test.go
- test/env/data.go
- test/integration/bundle/suite.go
- test/smoke/suite_test.go
Support https://github.com/cert-manager/trust-manager/issues/10
Add a new API Secret under taget to allow creating secret format CA certificates.
This is compatible with existing ConfigMap and can co-exist or exist alone.
> feat: support secret as a target

- Makefile
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.yaml
I fully accept that the `provision-buildx` stuff is weird and we should change it or document it better - but this seems to work for now, and I can run the build commands succesfully locally while they still (usually 😂 ) pass in CI
> Fix build on macOS / values.yaml wording tweaks 

- deploy/charts/trust-manager/templates/deployment.yaml
When the `initcontainer` was added, we forgot to add the option to disable seccompProfile for that container.
This PR fixes that issue.
> Make seccompProfile optional in initContainer

- deploy/charts/trust-manager/templates/certificate.yaml
since this cert is self-signed, its subject will match its issuer
it's valid to have an empty subject, but not an empty issuer
> add a CN for the trust-manager certificate

- Dockerfile
- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
- trust-packages/debian/Containerfile
- trust-packages/debian/go.mod
Upgrade all go versions & go.mod files to 1.21
> Upgrade go to 1.21

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.yaml
This PR enables users to configure the `priorityClassName` field in the helm chart
> Allow configuring of the priorityClass

- go.mod
- hack/tools/go.mod
- trust-packages/debian/go.mod
This helps older versions of go parse these directives
Specifically, our build process for the default trust package locally depends on trust-manager@main, but older releases (the release-0.6 branch) use go 1.20 and won't be able to parse them.
This tangle isn't ideal, but for future versions (i.e. when we can retire the release-0.6 branch and all supported versions use go 1.21) we can move past this and add the patch releases to our go directives again.
Motivation: [This test failure](https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_trust-manager/208/pull-trust-manager-smoke/1716817463552774144) for the release-0.6 branch. Specifically:
>  #15 20.52 go: github.com/cert-manager/trust-manager/cmd/validate-trust-package@main (in …
> Remove patch versions from go directives

- pkg/bundle/sync.go
Renamed some functions and removed some unnecessary type casting.
> Cleanup patch functions Secret and ConfigMap targets

- OWNERS
Ref. the [cert-manager governance document](https://github.com/cert-manager/community/blob/main/GOVERNANCE.md#approver), I would like to apply for the approver role in trust-manager.
Since becoming a reviewer, I have reviewed several PRs in this project. Many small ones, but also some larger ones. In the last category I would like to mention: https://github.com/cert-manager/trust-manager/pull/89 https://github.com/cert-manager/trust-manager/pull/161 https://github.com/cert-manager/trust-manager/pull/178 https://github.com/cert-manager/trust-manager/pull/184 https://github.com/cert-manager/trust-manager/pull/198
Sponsor: @inteon
> Add erikgb to project approvers

- deploy/charts/trust-manager/templates/webhook.yaml
Our releases were failing to deploy because it was trying to call a webhook that didn't exist. Our installation had the helm package in one namespace, but the resources for that package in another namespace. The result was something like this:
```
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "[trust.cert-manager.io](http://trust.cert-manager.io/)": failed to call webhook: Post "[https://trust-manager.helm-charts.svc:443/validate-trust-cert-manager-io-v1alpha1-bundle?timeout=5s](https://trust-manager.helm-charts.svc/validate-trust-cert-manager-io-v1alpha1-bundle?timeout=5s)": service "trust-manager" not found
```
The service actually exists in the `trust-manager` namespace, not the `helm-charts` namespace.
After examining the code it …
> Use proper namespace for webhook

- deploy/charts/trust-manager/templates/clusterrole.yaml
We made a mistake in https://github.com/cert-manager/trust-manager/pull/191.
To migrate from CSA to SSA, we need to be able to UPDATE the resource (not the sub-resource).
The update operation is performed here: https://github.com/cert-manager/trust-manager/blob/0418012f3617d222d0a5ae337e9168534f6f2005/pkg/bundle/bundle.go#L491
To avoid these problems in the future, we should run our integration tests using a non-admin service account (so we also test our RBAC configs).
> FIX: For CSA to SSA migration, we need UPDATE permission on the resource (not the sub-resource)

- cmd/trust-manager/app/app.go
- deploy/charts/trust-manager/templates/role.yaml
- deploy/charts/trust-manager/templates/rolebinding.yaml
This pull request separates the lease permissions to their own role and role binding in the namespace where trust-manager will be installed. See #224 for more details.
> Allow permissions to put the leases in the trust-manager namespace, not the trust namespace

- Makefile
- hack/update-debian-trust-package.sh
- make/trust-package-debian.mk
Fixes #246 - see that issue for details!
> Improve package CI error handling

- pkg/bundle/bundle.go
- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
While working on something else, I discovered that if a bundle specifies any additional format in targets, the JKS/PKCS12 is encoded for each and every target configmap/secret. This seems wrong to me, as encoding in these binary trust store formats is a quite heavy operation.
This PR moves the encoding of any additional target formats into `buildSourceBundle` method - which is executed once per bundle reconciliation. I tried to make this fix/refactoring as minimal as possible to not affect the WIP on https://github.com/cert-manager/trust-manager/pull/235 too much. We could eventually improve this even more in a follow-up PR - especially the tests, which have a lot of duplication at present.
> fix: should encode additional target format just once per bundle reconcile

- Makefile
I noticed this while looking into #240
On at least macos 14.1 (sonoma) the paste utility seems to require a filename to be specified; before this change, the `API_DIRS` variable fails with the following error:
> usage: paste [-s] [-d delimiters] file ...
This avoids us spinning up a separate shell when evaluating `API_DIRS`, since `GO_MODULE` already contains the value we want.
This change also changes the variable assignments; make variables are very confusing, but `:=` should only evaluate at startup while `=` will evaluate every time the variable is used.
See [these docs](https://www.gnu.org/software/make/manual/html_node/Recursive-Assignment.html) for how `=` works, and [these](https://www.gnu.org/software/make/manual/html_node/Simple-Assignment.html) for `:=`. From the first link:
> …
> Fix apply configuration generation on macOS

- Makefile
- make/trust-manager-build.mk
- make/trust-package-debian.mk
These commits help when developing on non-amd64 architectures.
> Better handling of local arch differences

- pkg/bundle/sync.go
- test/integration/bundle/suite.go
When checking target keys using managed fields, we must also check `binaryData` field in target configmaps.
Fixes #259
> fix: should reconcile targets consistently

- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/applyconfigurations/trust/v1alpha1/bundle.go
While trying to migrate one of our operators to SSA, I realized a bug in https://github.com/cert-manager/trust-manager/pull/217. Bundle is a cluster-scoped resource, and needs an additional marker to generate a correct AC constructor. Please see https://kubernetes.slack.com/archives/C02MRBMN00Z/p1702911424438589 for details.
> fix: apply-configuration gen for Bundle (cluster-scoped)

- Dockerfile
- Makefile
- trust-packages/debian/Containerfile
See https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
This PR adds that blogpost for this repo. It also allows me to build trust-manager on macOS, when I currently cannot because of bugs in emulation when building for different platforms.
This will also improve performance as well as fixing the build on macOS.
We might want to use a different process down the road, but I'm confident this is an improvement to the status quo.
> Do more of the container build process locally

- Makefile
`make image` is not as well defined as `make trust-package-debian-save` or `make trust-manager-load`, but it seems reasonable to have it available as a test when developing trust-manager.
If `make image` also applies to the trust package, it requires that users come up with a value for `DEBIAN_TRUST_PACKAGE_VERSION` which most users won't be able to guess.
Most users should be using the provided commands for loading trust-manager into a kind cluster when developing, which sidesteps this problem entirely.
It feels like the simplest thing here is to have `make image` be an alias for `make trust-manager-save`.
> Don't build trust bundle images using make image

- pkg/util/pem_test.go
- test/dummy/certificates.go
- test/dummy/certificates_test.go
This adds some checks on the new dummy expired certificate, and changes how we test filtering of expired certs.
I'd rather not check the exact output of `ValidateAndSanitizePEMBundleWithOptions` to check for cert expiry, since that'll be brittle if we change what that function outputs. This test instead explicitly checks for expired certs.
> Test tweaks following #273

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.yaml
> docs: updating chart values.yaml for better comment docs

- pkg/bundle/util_test.go
While working on https://github.com/cert-manager/trust-manager/pull/239, I discovered that `setBundleCondition` is not tested as it's used after migration to SSA. To reduce the size of the other PR I am suggesting to fix this in a separate PR.
/cc @inteon
> test: should test setBundleCondition as it's used

- Makefile
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- deploy/charts/trust-manager/values.yaml
- hack/update-codegen.sh
Adds the new `crds.keep` option which prevents us from incidentally removing the CRDs when uninstalling the chart.
See https://github.com/cert-manager/cert-manager/pull/6719 for more info.
> Add 'crds.keep' options to generated CRDs

- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/templates/clusterrole.yaml
- deploy/charts/trust-manager/templates/clusterrolebinding.yaml
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/metrics-service.yaml
- deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
- deploy/charts/trust-manager/templates/role.yaml
- deploy/charts/trust-manager/templates/rolebinding.yaml
- deploy/charts/trust-manager/templates/serviceaccount.yaml
- deploy/charts/trust-manager/templates/webhook.yaml
- use the same include label statements everywhere & same as cert-manager uses
- adds the common labels to the pod template
- adds the common labels to resource that were missing them
> Helm: Uniformize all label include statements & add labels to pod template

- pkg/bundle/sync.go
In #296  user discovered that Java's keytool was unable to read PKCS#12 files generated by trust-manager which had no password set. We've not dug into why, but presumably keytool's implementation treats an empty password the same as a missing password somehow.
This wasn't caught in tests because our PKCS#12 library can parse the resulting files just fine.
By changing to use the "passwordless" encoder when no password is present, we can create files which both our tests and keytool can read. It's possible that some other tools can't handle the passwordless encoder and could break, but Java is (anecdotally) what we'd expect to be the largest consumer of PKCS#12 trust stores, so we'll optimise for that.
No test is provided here because keytool requires a JRE and it feels like too much to add …
> Fix passwordless pkcs12 files for Java

- deploy/charts/trust-manager/templates/deployment.yaml
This helps to avoid disk exhaustion attack; 50MB seems to be a reasonable level to start at
> Set a size limit on emptyDir

- pkg/bundle/sync.go
- pkg/bundle/sync_test.go
- pkg/util/cert_pool.go
- pkg/util/cert_pool_test.go
> Improve certificate deduplication operation

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/NOTES.txt
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
* Fixed a copy-paste typo in the help text for podDisruptionBudget
* Added some warnings to the NOTES.txt file to tell the user about production readiness values they should use
```sh
$ helm upgrade trust-manager bin/chart/trust-manager-v1.14.1.tgz --install --create-namespace --namespace venafi --values values.yaml
Release "trust-manager" has been upgraded. Happy Helming!
NAME: trust-manager
LAST DEPLOYED: Wed Feb 28 17:15:33 2024
NAMESPACE: venafi
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
⚠️  WARNING: Consider increasing the Helm value `replicaCount` to 2 if you require high availability.
⚠️  WARNING: Consider setting the Helm value `podDisruptionBudget.enabled` to true if you require high availability.
trust-manager v1.14.1 has been deployed successfully!
Your installation …
```
> Production readiness Helm chart tweaks

- Makefile
Enable Trust Manager for s390x architecture. This is pre-req required for trust bundle integration for knative eventing.
> enable trust manager on s390x

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
This PR fixes #295 so we can merge it ahead of a release. I cherry-picked the commit from #295 so that @niklastanner would still get credit for their contribution.
Since I want to release soon, I'm cherry-picking and fixing in my own PR so that we can move quickly!
> initContainer Resource Block: Fix #295 for merging

- go.mod
We should build with 1.22.1 for a release since we use the 1.22 tag: https://github.com/cert-manager/trust-manager/blob/b4a5572d0d17f6b7d80f43aee5b4254bd476d9e8/Dockerfile#L16
This will ensure we're using the 1.22.1 toolchain though!
> Bump toolchain to latest to address CVE-2024-24783

- trust-packages/debian/Containerfile
Backport of #321 (reqiured for other PRs to pass CI)
> [release-0.9] Bump builder go to 1.22

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
This fixes the helm chart validation and adds documentation for this param
> Helm chart - document and add to schema nameOverride

- deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- pkg/apis/trust/v1alpha1/types_bundle.go
It seems like the print columns were left behind when removing the copy of `target` under `status` in https://github.com/cert-manager/trust-manager/pull/230 and when introducing the opt-in for secrets as targets in https://github.com/cert-manager/trust-manager/pull/193.
I tried to figure out a better way to show _either_ the configmap or the secret target key, but I don't know if JSONPath supports it. But a bundle could potentially specify both a configmap and secret as target, so two columns are probably best anyway.
Fixes https://github.com/cert-manager/trust-manager/issues/343
> Fix Bundle target print column

- deploy/charts/trust-manager/templates/clusterrole.yaml
- pkg/bundle/bundle.go
- pkg/bundle/controller.go
- pkg/bundle/sync.go
This PR simplifies the upgrade from CSA to SSA by using the helper provided by upstream Kubernetes and also used by `kubectl`. There is a theoretical change in behavior when upgrading after this PR, since the helper does not take the target configmap key into account when upgrading. Which means there could potentially be another operator/controller using the c/r regression field manager. I still think the simplification of code and RBAC is worth this minor risk.
> Simplify managed fields upgrade from CSA to SSA

- pkg/bundle/bundle_test.go
- pkg/bundle/sync_test.go
- pkg/webhook/validation_test.go
- test/smoke/suite_test.go
The function [klogr,New](https://pkg.go.dev/k8s.io/klog/v2/klogr#New) has been deprecated. Instead of migrating to the suggested replacement, I propose to use [ktesting.NewTestContext](https://pkg.go.dev/k8s.io/klog/v2@v2.120.1/ktesting#NewTestContext) in tests instead - which is already in use in this project.
For trust-manager (main) I would suggest migrating to the relatively new GO stdlib log (slog) - with a target to address https://github.com/cert-manager/trust-manager/issues/282. I will try to do this in a follow up PR.
> Replace deprecated klog.New in tests with ktesting.NewTestContext

- cmd/trust-manager/app/options/options.go
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
In this PR I propose to introduce slog.Handler as a backend for logr (and klog) - as documented [here](https://github.com/go-logr/logr?tab=readme-ov-file#using-a-sloghandler-as-backend-for-logr).
I am doing a minimal change in this PR where my primary goal is to add support for a structured log format (ref.  https://github.com/cert-manager/trust-manager/issues/282).
**NOTE**: This might break for some users, depending on if/how they parse trust-manager log output. I cannot imagine the slog text format (the new default) is the same as the deprecated klog format. We always try to avoid breaking changes, but I think a change is required here anyway - since the currently used klog format is deprecated.
Fixes https://github.com/cert-manager/trust-manager/issues/282
> Add support for JSON logging format

- pkg/bundle/bundle.go
Currently, the code for syncing target configmaps and secrets is separate - even if the logic should be the same. This doesn't make it tempting to add new features to bundle targets. In this PR I made an attempt to duplicate some of the code. We could probably do more, but let me know what you think before I spend more time on this! ☺️
> Deduplicate code for syncing target configmaps and secrets

- make/00_mod.mk
In #315 we added support for s390x, but this was unintentionally removed in v0.10.0 due to the makefile modules changes. This PR re-adds support for s390x.
It depended on a new base image being built for s390x (via https://github.com/cert-manager/base-images/pull/5), which wasn't previously available.
Confirmed locally that `make oci-build-manager oci-build-package_debian` builds s390x versions of both.
> re-add support for s390x

- pkg/bundle/bundle.go
- pkg/bundle/source.go
- pkg/bundle/source_test.go
This is a minor refactoring changing the input when building bundle data. Main benefit now is just simpler tests, but I am considering future changes that will benefit from this initial change.
/cc @inteon
> refactor: build bundle data from relevant spec

- pkg/bundle/bundle_test.go
- pkg/bundle/source.go
- pkg/bundle/source_test.go
- test/dummy/certificates.go
- test/env/data.go
- test/integration/bundle/suite.go
- test/smoke/suite_test.go
> Sort certificates in bundles to ensure deterministic behaviour

- cmd/trust-manager/app/app.go
- cmd/trust-manager/app/options/options.go
This change will prevent trust-manager from restart looping when kube API server is (over-)loaded. Most kubernetes operators increase this value as the default (15s) is too low under load.
> Add flags to configure LeaseDuration and RenewDeadline

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/webhook.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
This removes the hard dependency on cert-manager by allowing users to choose not to create a Certificate.
The extremely long lifetime of the cert is to remove the chance of it expiring in the lifetime of a typical cluster. Users who want rotation would be well advised to use cert-manager, which remains the default
> Add support for generating certificates with helm

- pkg/bundle/bundle.go
- pkg/bundle/target.go
Minor refactoring simplifying the SSA Patch calls.
/cc @inteon
> refactor: simplify SSA patch calls

- docs/api/api.md
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/source.go
- pkg/bundle/source_test.go
- test/integration/bundle/suite.go
This minor refactoring is extracted from https://github.com/cert-manager/trust-manager/pull/378, and the motivation is to solve circular package dependency issues.
Moving the constants to the API package seems like a good option, as the default passwords used for truststores is highly user-facing.
/cc @inteon
> refactor: move default truststore passwords to API

- pkg/bundle/bundle_test.go
- pkg/bundle/internal/truststore/types.go
- pkg/bundle/internal/truststore/types_test.go
- pkg/bundle/source.go
- pkg/bundle/source_test.go
This is another refactoring preparing for https://github.com/cert-manager/trust-manager/pull/378 - to avoid dependency issues. The proposed changes move all types to encode truststores into a dedicated (internal) package.
> refactor: extract truststore encoding to internal package

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
Spotted by @wallrj in https://github.com/cert-manager/istio-csr/pull/365
> Fix example of topologySpreadConstraints to reference trust-manager

- pkg/bundle/bundle.go
- pkg/bundle/internal/ssa_client/migrate.go
- pkg/bundle/internal/ssa_client/patch.go
- pkg/bundle/target.go
With some additional improvements that made sense when doing this. The main motivation is to reduce the size of https://github.com/cert-manager/trust-manager/pull/378, as I need the `FieldManager` constant available in a new package without getting circular dependencies.
The package name `ssa_client` annoys me a bit. 😉 I think the name should be just `client`. I was tempted to change this, but let's leave it for now - as it will require us to resolve package name import conflicts. It should be possible to do by creating type aliases in our `client` package. I've seen that c/r does this a lot.
> refactor: move FieldManager to more available package

- pkg/bundle/bundle_test.go
- pkg/bundle/controller.go
- pkg/bundle/source_test.go
- pkg/bundle/target_test.go
- test/env/data.go
When an identifier name collides with an import alias, my IDE gets confused, making me less effective when coding. This PR fixes all current collisions, but I wonder if golangci-lint might have a linter that can detect this? For one of the collisions, I found it more convenient to fix this by extracting a reusable function avoiding duplicated code.
> refactor: fix name and import alias collisions

- pkg/bundle/bundle.go
- pkg/bundle/source.go
- pkg/bundle/target.go
- pkg/bundle/target_test.go
Extracted from https://github.com/cert-manager/trust-manager/pull/378, and obtaining a cleaner separation of source and target is required to move the target logic to a dedicated package.
> refactor: dedicated target data struct

- pkg/bundle/bundle_test.go
- pkg/bundle/internal/ssa_client/patch.go
- pkg/bundle/target_test.go
Extracted from https://github.com/cert-manager/trust-manager/pull/378 - which should show the motivation for this refactoring: I want to extract the code for handling configmap/secret targets out of the huge bundle package. The test utility function moved in this PR is used in tests that I want to move, but also in tests that should remain in the package.
If you think there is a better location (package) for this test utility code, please let me know.
> refactor: move function for creating managed field entries

- pkg/bundle/source.go
- pkg/bundle/source_test.go
Fixes https://github.com/cert-manager/trust-manager/issues/426?
~~We have a test that asserts an error when the bundle is empty. I doubt if this is correct, and to fix https://github.com/cert-manager/trust-manager/issues/426 properly, I think this behavior must go. We could eventually assert that a Bundle is invalid if it doesn't contain at least one source spec. But that is better done with the webhook (or API CEL expression) IMO.~~
UPDATE: After discussing this PR in today's stand-up, we decided to keep the existing (and tested) behavior where a target bundle needs to contain at least one certificate, at least for now. This means that this PR only fixes a minor bug: before this PR it would error if any source selector selects no sources. Now this is ok, but the resulting bundle must …
> fix: don't error if source selector selects no sources

- pkg/bundle/target.go
The main goal of this refactoring is to **move the deletion of target configmap/secret out of the patch functions**. The end goal is to provide functions that can be reused in the new pull-target feature I am working on. When the user creates the target resource, it does not make sense for trust-manager to delete it (as a side effect of patching it).
I have renamed some variables to avoid shadowing in https://github.com/cert-manager/trust-manager/pull/378.
Relates to https://github.com/cert-manager/trust-manager/pull/378
> refactor: reduce duplication in sync target functions

- pkg/bundle/bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/controller.go
- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/target/target_test.go
- pkg/bundle/source.go
- pkg/bundle/source_test.go
This is a major refactor of the bundle target area. The main motivation is to prepare the grounds for https://github.com/cert-manager/trust-manager/issues/58 and https://github.com/cert-manager/trust-manager/issues/222.
~~The refactoring became larger because I had to move some fields and functions to avoid circular package dependencies. I would be happy to split these changes out in pre-PRs if desired.~~ Multiple pre-PRs merged now.
> refactor: establish target.Reconciler

- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/truststore/types_test.go
I would still prefer if we could perform an unconditional SSA of target resources and avoid the complex and error-prone target "needs update" logic. This could eventually address https://github.com/cert-manager/trust-manager/issues/433 and in general, ensure trust-manager target resources are more up-to-date.
It seems like trust-manager truststores are now deterministic, except PKCS#12 truststores with a custom (non-empty) password. I attempted to fix this but didn't manage to.
> test: add tests for truststore deterministic

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
**Pull Request Motivation**
Some environments have admission webhooks that might mandate specific labels or annotations. This change allows chart users to set labels and/or annotations in the Secret created by the Certificate resources.
Close https://github.com/cert-manager/trust-manager/issues/453
> feat(helm): add secretTemplate-ing to certificate

- deploy/charts/trust-manager/Chart.yaml
Having a random version checked into Git is confusing for users.
Fixes https://github.com/cert-manager/trust-manager/issues/489
/cc @inteon @SgtCoDFish
> Set dummy Helm chart versions

- .github/workflows/debian-trust-package-release.yaml
- .github/workflows/release.yaml
- RELEASE.md
- klone.yaml
- make/00_mod.mk
- make/02_mod.mk
- make/_shared/helm/helm.mk
Adds logic for pushing the Helm chart to an OCI registry (and adding a non-v-prefixed tag)
See https://github.com/cert-manager/makefile-modules/pull/219 for more info.
This change was used to create an alpha release:
`helm install approver-policy oci://quay.io/jetstack/charts/trust-manager --version 0.15.0-alpha.0`
`helm install approver-policy oci://quay.io/jetstack/charts/trust-manager --version v0.15.0-alpha.0`
> Add Helm chart OCI release to GH automation

- .github/workflows/debian-trust-package-release.yaml
- .github/workflows/debian-trust-package-upgrade.yaml
Fixes this broken action: https://github.com/cert-manager/trust-manager/actions/runs/12498139714
> Add 'fetch-depth: 0' to Debian trust bundle GH checkout action

- go.mod
Preparations for https://github.com/cert-manager/trust-manager/pull/510 as K8s 1.32 dependencies require Go 1.23.
It seems like Go 1.23 rejects negative serial numbers by default in [x509.ParseCertificate](https://pkg.go.dev/crypto/x509#ParseCertificate), but the old behavior can be restored - as least as a short-term fix.
Long-term fix is probably to ensure our default trust bundles don't contain offending certificates. Maybe https://github.com/cert-manager/trust-manager/issues/183?
> Bump to Go 1.23 (and allow certificates with negative serial numbers)

- go.mod
- make/test-unit.mk
- pkg/bundle/source.go
- pkg/compat/negative_serial_number.go
- pkg/compat/negative_serial_number_godebug_test.go
- pkg/compat/negative_serial_number_test.go
- pkg/compat/parse_cert.go
- pkg/compat/util_test.go
- pkg/util/cert_pool.go
See also [slack](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1734105432142589).
Go 1.23 changes ParseCertificate to no longer accept negative serial numbers (in line with specs).
This breaks the trust package we provide which contains an older CA with a negative serial number in it.
As a special case for just this one cert, we handle the error and skip including the cert rather than failing the entire bundle because of this cert.
This also adds tests for the behavior of the new `compat.ParseCertificate` function, both with the GODEBUG workaround set and unset.
Users who _need_ to trust this CA will for the foreseeable future still be able to include it by setting the `GODEBUG` environment variable when running trust-manager.
> RELEASE BLOCKER: Add special case handling of cert with negative serial number

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/_helpers.tpl
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/serviceaccount.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
The deployment of trust-manager in an AKS cluster raised a high-severity security finding from Azure Defender, recommending the disabling of automounted service account tokens to prevent potential misuse by compromised pods. 
This PR addresses the issue by allowing users to disable`automountServiceAccountToken` while enabling them to use volumes to access the token. This approach is based on the requirement that `trust-manager` needs the token to interact with the Kubernetes API.
With the proposed changes, you can deploy the chart using the following configuration:
```yml
automountServiceAccountToken: false
serviceAccount:
automountServiceAccountToken: false
volumes:
- name: serviceaccount-token
projected:
defaultMode: 0444
sources:
- serviceAccountToken:
expirationSeconds: 3607
path: …
```
> feat(helm): Allow to configure automountServiceAccountToken

- make/test-integration.mk
- test/integration/bundle/integration.go
After https://github.com/cert-manager/makefile-modules/pull/214 is available in this project, we can simplify the integration test setup to use the generated CRD manifests.
> Simplify integration test setup

- klone.yaml
- make/00_mod.mk
- make/_shared/go/01_mod.mk
- make/_shared/oci-build/00_mod.mk
- make/_shared/oci-build/01_mod.mk
- make/debian-trust-package.mk
In https://github.com/cert-manager/makefile-modules/pull/241 the `oci_additional_layers_package_debian` variable was renamed to `oci_package_debian_additional_layers`.
> Upgrade oci-build makefile module

- .github/workflows/debian-trust-package-release-bookworm.yaml
- .github/workflows/debian-trust-package-upgrade-bookworm.yaml
- make/00_debian_bookworm_version.mk
- make/00_mod.mk
- make/02_mod.mk
- make/debian-trust-package-bookworm.mk
- make/debian-trust-package-fetch.sh
- make/debian-trust-package.mk
- make/test-smoke.mk
- make/validate-trust-package.mk
- pkg/bundle/controller.go
- trust-packages/debian/README.md
Also switches to use the new trust package by default in tests, but not yet for trust-manager properly (since there's no image built yet - that'll come in a follow-up PR).
This is a brute force approach of pretty much copying everything from the existing trust package.
> Add build for trust package based on Debian bookworm

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
- make/00_mod.mk
- make/test-smoke.mk
This changes trust-manager to use the new Debian Bookworm trust package by default. I've tested this locally by doing the following:
1. Installed trust-manager v0.15.0 using the "old" default package
2. Created a bundle, saved the resulting `ConfigMap`
3. Manually edited the trust-manager deployment to use the new default package
4. Watched the ConfigMap, saw it get updated
5. Saved the new ConfigMap and confirmed it was different
The smoke test also uses the new package in this PR
Closes https://github.com/cert-manager/trust-manager/issues/183
> Use the debian bookworm package for testing + releases

- design/20241124-rename-bunde-to-clusterbundle.md
Proposal on how to implement https://github.com/cert-manager/trust-manager/issues/63.
The proposed solution is based on [input from "the greater community"](https://kubernetes.slack.com/archives/C0EG7JC6T/p1732370214737539). 🥇
> Migration Design: Rename Bundle to ClusterBundle

- make/test-integration.mk
- test/env/ginkgo.go
Fixes a few issues:
1. Integration test output had "e2e" in it, which is misleading
2. Integration test output had the same name as the smoke tests, leading to output for one overwriting the other
3. E2E test JUnit output was configured in both Go code and using CLI flags passed to ginkgo, which led to error messages in smoke tests
Example of smoke test errors (from [here](https://storage.googleapis.com/cert-manager-prow-artifacts/pr-logs/pull/cert-manager_trust-manager/550/pull-trust-manager-smoke/1887999307181723648/build-log.txt)):
> Could not open /logs/artifacts/test_smoke_junit-go-e2e.xml:
> open /logs/artifacts/test_smoke_junit-go-e2e.xml: no such file or directory
> Tweak JUnit config for e2e / integration tests

- cmd/trust-manager/app/app.go
- cmd/trust-manager/app/options/options.go
- pkg/bundle/bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/controller.go
- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/target/target_test.go
- pkg/bundle/source.go
- pkg/webhook/validation.go
- pkg/webhook/validation_test.go
- pkg/webhook/webhook.go
- test/integration/bundle/suite.go
- test/smoke/suite_test.go
As noted in https://github.com/cert-manager/trust-manager/pull/442#discussion_r1946705109, it seems like we prefer to use the Context to pass around the logger. I've also been annoyed by this when attempting to refactor code. 🦄 
This PR removes all use of Logger as fields in structs - except for the CertPool, which will probably be refactored out of this repository to a more reusable module.
This change will most certainly change the looks of trust-manager logs. Instead of creating a many sub-loggers, we now rely on controller-runtime to initialize the logger supplied with Context. To my experience it does a pretty good job enriching the structured logger with relevant key/value pairs.
> Use Context to pass Logger

- .github/workflows/debian-trust-package-upgrade-bookworm.yaml
- RELEASE.md
Also fixes some trailing whitespace
See #545 for a similar change.
> Add fetch-depth:0 to bookworm upgrade job

- cmd/trust-manager/app/app.go
- cmd/trust-manager/app/options/options.go
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
Fixes #499, by default the flag is true in order to preserve the original behavior
> add leaderElection flag to trust manager

- cmd/trust-manager/app/app.go
- cmd/trust-manager/app/ciphers_test.go
- cmd/trust-manager/app/options/options.go
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
This PR is introducing  Minimum TLS version and Ciphers Suite feature which were requested in issue #528.
> Introduce min-tls and ciphers-suite application options for webhook server

- test/integration/bundle/integration.go
- test/integration/bundle/validation_test.go
In https://github.com/cert-manager/trust-manager/pull/475, I added new integration tests to test validation implemented using CEL (was validating webhook). This PR adds these new tests without migrating to CEL - as suggested by @SgtCoDFish! 👍 The validating webhook is now enabled in the integration test.
/cc @SgtCoDFish
> Add validating admission integration tests

- make/test-smoke.mk
... failing with newer versions of Ginkgo, ref. CI failing in https://github.com/cert-manager/trust-manager/pull/572.
Ginkgo CLI is now validating commands more strictly than it used to, and I think our current commands broke with https://github.com/onsi/ginkgo/releases/tag/v2.23.1.
> Fix Ginkgo commands

- deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/truststore/types.go
- pkg/bundle/internal/truststore/types_test.go
This adds a profile option mirroring the values allowed here https://github.com/cert-manager/cert-manager/blob/e1a1ea959aa23ed72d9d7614b34d58ef420ad1d2/pkg/apis/certmanager/v1/types_certificate.go#L521. 
Fixes #457
FYI have not yet managed to get all the tests to run locally but the tests covering the truststore package itself seems to work fine.
> Added PKCS12 profile option

- deploy/charts/trust-manager/templates/poddisruptionbudget.yaml
The current implementation does not account for namespace overrides via Helm Values for the PDB resource.
Instead, it uses `Release.Namespace` or, if undefined, it falls back to the 'default' namespace, which is inconsistent with how the namespace field is populated for all the other resources.
This PR makes the population of the `namespace` field consistent with all the other resources in the Helm Chart.
> Fixup PDB namespace population logic

- deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/apis/trustmanager/v1alpha2/types_cluster_bundle.go
While working on https://github.com/cert-manager/trust-manager/pull/486, I noticed that the API doc (probably copied from cert-manager) is slightly misleading for trust-manager use. This PR attempts to fix this.
/cc @terricain @SgtCoDFish
> Fix slightly misleading PKCS#12 profile API docs

- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/extra-manifests.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
This simply allows the addition of further resources through "extraObjects" in the values file, e.g. network policies.
Fixes #584
> Add extraObjects to Helm chart

- trust-packages/debian/LICENSE
- trust-packages/debian/LICENSES
Add LICENSE file to the `trust-packages/debian` folder, which will be included in the trust-package OCI image.
https://github.com/cert-manager/makefile-modules/pull/284 will enforce this.
> Add missing LICENSE file

- LICENSES
- deploy/charts/trust-manager/README.md
- deploy/charts/trust-manager/templates/certificate.yaml
- deploy/charts/trust-manager/templates/clusterrole.yaml
- deploy/charts/trust-manager/templates/clusterrolebinding.yaml
- deploy/charts/trust-manager/templates/deployment.yaml
- deploy/charts/trust-manager/templates/metrics-service.yaml
- deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
- deploy/charts/trust-manager/templates/poddisruptionbudget.yaml
- deploy/charts/trust-manager/templates/role.yaml
- deploy/charts/trust-manager/templates/rolebinding.yaml
- deploy/charts/trust-manager/templates/serviceaccount.yaml
- deploy/charts/trust-manager/templates/webhook.yaml
- deploy/charts/trust-manager/values.schema.json
- deploy/charts/trust-manager/values.yaml
Adding a way for the users to add annotations for all the trust-manager resources. This PR is being raised as part of this [issue](https://github.com/cert-manager/trust-manager/issues/597) which indicates a use case for using argocd sync-waves.
Fixes #597 
Close https://github.com/cert-manager/trust-manager/pull/214
> Adding common annotations for all the resources

- LICENSES
- go.mod
- go.sum
- pkg/bundle/bundle_test.go
- pkg/bundle/internal/truststore/types.go
- pkg/bundle/internal/truststore/types_test.go
- pkg/bundle/source_test.go
- test/env/data.go
This is a partial revert of https://github.com/cert-manager/trust-manager/pull/603, in particular changing JKS encoding to use the PKCS#12 encoder. Even if we tested this change on all Java LTS versions, it seems to have caused issues for users. I suggest to switch the encoder when we remove JKS from the Bundler/ClusterBundle spec.
Fixes https://github.com/cert-manager/trust-manager/issues/625
> Revert "Use PKCS#12 encoder to encode JKS"

- cmd/trust-manager/app/options/options.go
- pkg/bundle/bundle.go
- pkg/bundle/bundle_test.go
- pkg/bundle/controller.go
- pkg/bundle/controller/options.go
- pkg/bundle/internal/source/source.go
- pkg/bundle/internal/source/source_test.go
- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/target/target_test.go
- test/env/data.go
- test/integration/bundle/suite.go
- test/smoke/suite_test.go
This PR is a rework of https://github.com/cert-manager/trust-manager/pull/442, where I have tried to address the initial review by Ashley.
The main motivation for this PR, is to get closer to a solution to https://github.com/cert-manager/trust-manager/issues/58, as the bundle controller cannot be used directly for this use case. But also preparations for https://github.com/cert-manager/trust-manager/issues/245 , which is something I really would love to do.
I can identify a few more general improvements in this:
- Better modularization, though far from perfect yet.
- Removing the strange `target.Data` struct that was introduced to extract target processing.
> refactor: dedicated struct for building source data

- deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
- deploy/crds/trust.cert-manager.io_bundles.yaml
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/bundle/bundle_test.go
- pkg/webhook/validation.go
- pkg/webhook/validation_test.go
- test/integration/bundle/validation_test.go
This PR makes the bundle target spec optional, and also makes it possible to remove a target configmap/secret configuration. Somehow, we were validating this in our update validating webhook, but I consider it a bug.
Relates to https://github.com/cert-manager/trust-manager/pull/658. This backport of (non-breaking) allowing no targets will simplify the migration to `ClusterBundle`.
Also, removing the validation of the target key from the validating webhook, as the Bundle schema fully validates this.
> Make bundle target optional

- pkg/apis/trust/v1alpha1/conversion.go
- pkg/apis/trust/v1alpha1/conversion_test.go
- pkg/apis/trust/v1alpha1/types_bundle.go
- pkg/apis/trust/v1alpha1/zz_generated.conversion.go
- pkg/apis/trustmanager/v1alpha2/types_cluster_bundle.go
After scrutinizing the new (unpublished) `ClusterBundle` API, I found a few potential improvements. I have created separate commits for each change, so this PR is better reviewed commit by commit. A summary of the proposed API changes:
1. Make `.spec.target` optional. This was done for the current `Bundle` in https://github.com/cert-manager/trust-manager/pull/661.
2. Drop the source `includeAllKeys` field in favor of simple wildcard (`*` only) support in the source `key`. This change allows us to make the source `key` mandatory, thus simplifying overall validation. We can always make it optional later on, when adding support for key-less sources. Since I am planning to use https://pkg.go.dev/path#Match for matching keys, I also added regex pattern validation to the source `key` field.
3. …
> Final minor adjustments to new ClusterBundle API

- deploy/crds/trust-manager.io_clusterbundles.yaml
- pkg/apis/trustmanager/v1alpha2/types_cluster_bundle.go
- test/integration/bundle/cluster_bundle_validation_test.go
- test/integration/bundle/integration.go
This PR adds all API validations for the new `CLusterBundle` API that I was able to implement without adding a validating webhook. I have added a new "integration" test, based on envtest (simplified control plane), to test these validations. I suggested introducing CEL validations in https://github.com/cert-manager/trust-manager/pull/475, but the `Bundle` API wasn't really ready for it, as the expressions became way too complex. But in the new API, I think the CEL expressions are simple enough.....
Label selectors cannot currently be validated using CEL expressions (or OpenAPI schema) and require a webhook for validation. This is probably true for labels/annotations, even if Kubernetes is now providing the [format CEL library](https://kubernetes.io/docs/reference/using-api/cel/#kubernetes- …
> Add ClusterBundle API validations

- pkg/webhook/cluster_bundle.go
- test/integration/bundle/cluster_bundle_validation_test.go
- test/integration/bundle/integration.go
In this PR, I create a new validating webhook for `ClusterBundle` to cover the validations that still require a validating webhook. Hopefully, we can get rid of the validating webhooks completely when more validations are supported by Kubernetes CEL. I haven't added unit tests for the new validating webhook, but we should have very good coverage in the integration tests. This is mainly done because I hope we can get rid of the webhooks at some point.
Note: I have also made the "official" (Helm) `ValidatingWebhookConfiguration` more precise to avoid it from diverging from the simplified configuration used in the integration tests. This change should probably go in a separate PR, but I was a little in doubt. Please let me know what you think!
> Add ClusterBundle validating webhook

- pkg/bundle/bundle.go
- pkg/bundle/internal/source/source.go
- pkg/bundle/internal/source/source_test.go
- pkg/bundle/internal/target/target.go
- pkg/bundle/internal/target/target_test.go
This PR is a preparation for https://github.com/cert-manager/trust-manager/pull/702. As the new API is considerably more flexible, it makes sense to move the handling of "additional formats". In the `ClusterBundle` API, the format and password (in case of a truststore format) can be set per key in the target, so it doesn't make sense to prepare this in sources.
This PR is required before I can continue to migrate the current Bundle controller.
The test coverage is probably slightly reduced in this PR, as I am not testing with a custom password in the target test, just the default passwords. But we have other tests of the binary encoders, and I would prefer not spending extra time on the binary formats.
> Move additional formats handling from source to target
