cert-manager/trust-manager

deploy/charts/trust/Chart.yaml
deploy/charts/trust/README.md
deploy/charts/trust/values.yaml

Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>
/assign @jakexks

Fix image tag version to v0.1.0 in helm chart

---

README.md

See https://github.com/cert-manager/csi-driver/pull/80 for justification on logo changes

Update logo + link

---

deploy/charts/trust/README.md
deploy/charts/trust/templates/serviceaccount.yaml
deploy/charts/trust/values.yaml

Signed-off-by: Jacob Lorenzen <jacob@lorenzen.me>

feat: add image pull secrets to service account

---

SECURITY.md

Updates reference to jetstack/cert-manager to cert-manager/cert-manager in SECURITY.md

---

README.md

Use smaller cert-manager logo

---

Dockerfile

Signed-off-by: joshvanl <me@joshvanl.dev>
/assign @SgtCoDFish

Use `FROM scratch` for base image

---

Makefile
deploy/charts/trust/Chart.yaml
deploy/charts/trust/README.md
deploy/charts/trust/values.yaml

Signed-off-by: joshvanl <me@joshvanl.dev>
/assign @SgtCoDFish 
/hold
until #51 #50 are merged.
Once merged we can cut the release.

Update tag to v0.2.0 ready for release

---

deploy/charts/trust-manager/Chart.yaml

This should solve #14 
Signed-off-by: Jose Antonio <jacm.legend@gmail.com>

#14 Updating the apiVersion to v2

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/values.yaml

Update all versions (Helm chart version & app version) to v0.3.0.

Release v0.3.0

---

Makefile

Prefixes RELEASE_VERSION make var with `v` as it is expected to be in that form everywhere where it's used
Signed-off-by: irbekrm <irbekrm@gmail.com>

Prefix release version with 'v'

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/templates/deployment.yaml
deploy/charts/trust-manager/values.yaml

Put seccomp behind a flag

---

README.md

Signed-off-by: Hal Deadman <hdeadman@users.noreply.github.com>

fix broken link and old name references

---

SECURITY.md
make/trust-package-debian.mk

Variable name was changed but reference wasn't updated in #77 !

Fix incorrect variable reference which was missed in #77

---

README.md

https://github.com/cert-manager/website/pull/1160

Readme tweak taken from website#1160

---

deploy/charts/trust-manager/templates/webhook.yaml

As discussed in cert-manager biweekly meeting on 2023-01-25

Remove deprecated v1beta1 admission review version

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
deploy/charts/trust-manager/values.yaml
deploy/crds/trust.cert-manager.io_bundles.yaml
hack/update-codegen.sh
test/integration/bundle/integration.go

Signed-off-by: Max Sargent <maxsargentdev@gmail.com>

Make CRD installation optional

---

README.md

Follows on from #110 - specifically [this comment](https://github.com/cert-manager/trust-manager/pull/110#discussion_r1094523610)!

Review suggestion for README

---

deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/templates/deployment.yaml
deploy/charts/trust-manager/values.yaml

This PR is addressing issue #13 in the same manner done in the cert-manager helm chart

fixes #13 - Allow node selection based on nodeSelector, tolerations, affinities and topologySpreadConstraints

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/values.yaml

This is a followup to #117 to add some descriptions and tweak the helm chart doc output

Add descriptions for some helm chart fields

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/templates/deployment.yaml
deploy/charts/trust-manager/values.yaml

Fixes https://github.com/cert-manager/trust-manager/issues/148

Add new optional registry and digest Helm values

---

pkg/bundle/bundle_test.go
pkg/bundle/sync_test.go
pkg/bundle/util_test.go
pkg/webhook/validation_test.go
test/gen/bundle.go
test/integration/bundle/integration.go
test/integration/bundle/suite.go
test/smoke/suite_test.go

`k8s.io/utils/pointer` is deprecated

Move from k8s.io/utils/pointer to k8s.io/utils/ptr

---

pkg/apis/trust/v1alpha1/types_bundle.go
pkg/bundle/bundle.go
pkg/bundle/bundle_test.go
pkg/bundle/util.go
pkg/bundle/util_test.go
test/env/data.go

The updated util functions apply more directly on the fields of the bundle instead on the full bundle object.

Refactor util functions in preparation for SSA

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/values.yaml

preparing v0.7.0-alpha.0 release by replacing all versions

Release v0.7.0-alpha.0

---

pkg/bundle/controller.go

This PR fixes some duplicated code in the bundle controller setup.
/cc @inteon

Refactor bundle controller setup

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md

preparing the v0.7.0-alpha.1 release

Bump version to v0.7.0-alpha.1

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md

bumping all the version numbers

Preparing release v0.7.0-alpha.2

---

pkg/bundle/bundle.go
pkg/bundle/bundle_test.go

Missed in https://github.com/cert-manager/trust-manager/pull/193
On master, switching from the ConfigMap target type to the Secret target type was not supported correctly (or vice-versa).
I added additional tests and fixed this bug in this PR.

BUGFIX: support switching between target types

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md

Preparing for the v0.7.0-alpha.3 release.

Bump release version to v0.7.0-alpha.3

---

Makefile
deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md

Prepare release v0.7.0

---

README.md

Follows from something mentioned at the cert-manager booth at KubeCon!

Tweak readme to encourage use

---

test/integration/bundle/suite.go

Signed-off-by: Erik Godding Boye <egboye@gmail.com>
(cherry picked from commit 2800155a7c27caa87da9dda6edcb6e4ae2f9bc11)
This is a manual cherry-pick of https://github.com/cert-manager/trust-manager/pull/252, which is required to cherry-pick https://github.com/cert-manager/trust-manager/pull/260.
/cc @inteon

[release-0.7]: fix flaky tests by introducing komega

---

pkg/bundle/sync.go
test/integration/bundle/suite.go

Signed-off-by: Erik Godding Boye <egboye@gmail.com>
(cherry picked from commit 11288fa133db4108f825fcf9de2f98734335eeee)
Manual cherry-pick alternative to https://github.com/cert-manager/trust-manager/pull/265 - as the Go API has been changed.
/cc @inteon

[release-0.7]: should reconcile targets consistently

---

Makefile

Prompted by https://github.com/cert-manager/trust-manager/pull/251#issuecomment-1833521825

Improve makefile comments around image building

---

deploy/charts/trust-manager/Chart.yaml
deploy/charts/trust-manager/README.md

Cleanup of README.md and Chart.yaml to improve the artifacthub.io page.
- removes header from README.md
- adds extra annotations in Chart.yaml

Update README.md and Chart.yaml

---

OWNERS

This will allow @ThatsMrTalbot to lgtm PRs on this repo.

Add thatsmrtalbot as a reviewer

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/values.yaml

Updated the values.yaml file, so the README.md contains more useful information.

Improve OCI image options' Helm README.md documentation

---

deploy/charts/trust-manager/Chart.yaml

Introduced in https://github.com/cert-manager/trust-manager/pull/287

Fix typo in Chart.yaml icon URL

---

deploy/charts/trust-manager/values.schema.json
hack/tools/go.mod
hack/tools/go.sum

Bumps the dependencies in hack/tools

Upgrade tool dependencies

---

hack/update-debian-trust-package.sh

We updated our IMAGE_PLATFORMS variable in #315 which worked for the trust-manager build, but the current pipeline for trust-packages doesn't rebuild if an arch is missing. We could bump the version, but nothing is changing beyond a new arch so it seems a shame to force everyone to update when we could rebuild in place.
This PR changes the pipeline to also verify arches.
I tested locally by commenting out the `make ... trust-package-debian-push` line at the bottom of `hack/update-debian-trust-package.sh` and running `make ci-update-debian-trust-package` locally. It triggers a rebuild as expected.
```console
$ make ci-update-debian-trust-package
./hack/update-debian-trust-package.sh "quay.io/jetstack/cert-manager-package-debian" .0 …
```

Also check for correct architectures in trust package build

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/values.schema.json
deploy/charts/trust-manager/values.yaml

[release-0.9] Backport name override

---

.golangci.yaml
cmd/trust-manager/app/app.go
cmd/trust-manager/app/options/options.go
pkg/bundle/bundle.go
pkg/bundle/internal/ssa_client/bundle_status.go
pkg/bundle/sync.go
pkg/bundle/util.go
pkg/util/cert_pool.go
pkg/util/pem.go
pkg/util/pem_test.go
pkg/webhook/validation.go
pkg/webhook/validation_test.go
pkg/webhook/webhook.go
test/dummy/certificates.go
test/env/data.go
test/env/ginkgo.go
test/integration/bundle/integration.go
test/integration/bundle/suite.go
test/smoke/smoke_test.go
test/smoke/suite_test.go

Each commit removes one linter exception.

Fix all linter issues and un-ignore golanci-lint linter exceptions

---

deploy/charts/trust-manager/README.md
deploy/charts/trust-manager/templates/metrics-service.yaml
deploy/charts/trust-manager/templates/webhook.yaml
deploy/charts/trust-manager/values.schema.json
deploy/charts/trust-manager/values.yaml

feat(helm): dual-stack cluster service configuration

---

pkg/bundle/bundle_test.go
pkg/bundle/internal/target/target_test.go
pkg/bundle/source_test.go
pkg/bundle/util_test.go
pkg/util/pem_test.go

To mend https://github.com/cert-manager/trust-manager/pull/444.
/cc @inteon

ci: fix new copyloopvar lint errors

---

deploy/charts/trust-manager/templates/deployment.yaml

Add port naming for podMonitor support

Feat: Add port naming for podMonitor support

---

make/00_mod.mk

Leftovers after https://github.com/cert-manager/trust-manager/pull/491.
/cc @inteon

Remove unused Makefile variables

---

README.md

We got feedback that `make demo` doesn't work any more, so this is a quick refresh to improve the initial onboarding guide for anyone reading the README

Update readme to better reflect what we have today

---

.github/workflows/debian-trust-package-release-bookworm.yaml
make/00_debian_bookworm_version.mk

This should hopefully fix the error in https://github.com/cert-manager/trust-manager/actions/runs/13136435669/job/36652783894

Add fetch-depth to checkout action

---

.github/workflows/debian-trust-package-release-bookworm.yaml
make/00_debian_bookworm_version.mk

Fix syntax error

---

.github/workflows/debian-trust-package-release-bookworm.yaml
make/00_debian_bookworm_version.mk

Copy the other release action

---

.github/workflows/govulncheck.yaml
.github/workflows/make-self-upgrade.yaml
klone.yaml
make/_shared/go/base/.github/workflows/govulncheck.yaml
make/_shared/oci-build/00_mod.mk
make/_shared/oci-build/01_mod.mk
make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
make/_shared/tools/00_mod.mk

Manual run of self-upgrade logic

[CI] Self-upgrade merging self-upgrade-main into main

---

OWNERS

I have created 3 PR to trust-manager, mostly recently:
I have also reviewed many more PRs:
My specialism is usually not the code itself but everything around the code that makes it useful to people. You might consider it developer experience or similar.
/cc @erikgb @SgtCoDFish

feat: Add hawksight as reviewer

---

LICENSES
go.mod
go.sum
pkg/bundle/internal/ssa_client/patch.go
pkg/bundle/internal/target/target.go

Triggered by https://github.com/cert-manager/trust-manager/pull/711, which appeared a bit odd. 😉

Eliminate multiple sigs.k8s.io/structured-merge-diff deps
